# Generated by Django 2.2 on 2019-04-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190424_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credit_card_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
