# Generated by Django 2.2 on 2019-04-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190424_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credit_card_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
