# Generated by Django 2.2 on 2019-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190429_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
