# Generated by Django 2.2 on 2019-05-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_friend_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='is_approved',
        ),
    ]
