# Generated by Django 2.2 on 2019-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190429_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
